const initState = {
  laptops: [
    {
      id: "668282",
      name: "Apple MacBook Pro 2022",
      itemImg: [
        "images/6450858_sd.webp",
        "images/6450858cv1d.jpeg",
        "images/6450858cv3d.jpeg",
        "images/6450858cv4d.jpeg",
        "images/6450858cv7d.jpeg",
      ],
      description1:
        "Apple MacBook Pro 2022 - Grey - Apple MacBook Pro 2022 - Grey",
      description2: "",
      newItemPrice: "1200",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "872819",
      name: "Apple MacBook Air 2020",
      itemImg: [
        "images/6489618cv11d.png",
        "images/6489618cv12d.jpeg",
        "images/6489618cv14d.jpeg",
        "images/6489618cv15d.jpeg",
      ],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1112778",
      name: "Apple MacBook Air 2020",
      itemImg: [
        "images/6489836_sd.png",
        "images/6489836cv11d.jpeg",
        "images/6489836cv12d.jpeg",
        "images/6489836cv13d.jpeg",
        "images/6489836cv14d.jpeg",
      ],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "187818",
      name: "Apple MacBook Air 2020",
      itemImg: [
        "images/6489842_sd.webp",
        "images/6489842cv11d.jpeg",
        "images/6489842cv12d.jpeg",
      ],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "198811",
      name: "Apple MacBook Air 2020",
      itemImg: [
        "images/5721600_sd.webp",
        "images/5721600cv11d.jpeg",
        "images/6489842cv12d.jpeg",
        "images/5721600cv13d.jpeg",
        "images/5721600cv14d.jpeg",
      ],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8882738",
      name: "Apple MacBook Air 2020",
      itemImg: [
        "images/6455369_sd.webp",
        "images/6455369_rd.jpeg",
        "images/6450858cv7d.jpeg",
        "images/6450858cv4d.jpeg",
      ],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },
    {
      id: "7716272",
      name: "Apple MacBook Air 2020",
      itemImg: ["images/6455369_sd.webp"],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "991838",
      name: "Apple MacBook Air 2020",
      itemImg: ["images/6413734_sd.png"],
      description1: "Apple MacBook Air 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "6262719",

      name: "Apple MacBook Pro",
      itemImg: [
        "images/6509650_sd.png",
        "images/6509650cv11d.jpeg",
        "images/6509650cv12d.jpeg",
      ],
      description1: "Apple MacBook Pro 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "7711882",

      name: "Apple MacBook Pro",
      itemImg: [
        "images/6489721cv12d.webp",
        "images/6489721_sd.jpeg",
        "images/6515448cv11d.jpeg",
      ],
      description1: "Apple MacBook Pro 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "726278",

      name: "Apple MacBook Pro",
      itemImg: ["images/6515448_sd.png", "images/6515448cv12d.jpeg"],
      description1: "Apple MacBook Pro 2020",
      description2: "",
      newItemPrice: "1100",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 16,
      brand: "Mac",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "881738",

      name: "ASUS",
      itemImg: [
        "images/6492794_rd.webp",
        "images/6492794_sd.jpeg",
        "images/6492794cv1d.jpeg",
        "images/6492794cv3d.jpeg",
        "images/6492794cv10d.jpeg",
      ],
      description1: "ASUS - White",
      description2: "",
      newItemPrice: "1250",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 13,
      brand: "asus",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "772881",

      name: "ASUS",
      itemImg: [
        "images/6501561_sd.png",
        "images/6501561_rd.jpeg",
        "images/6501561ld.jpeg",
        "images/6501561cv1d.jpeg",
        "images/6501561cv3d.jpeg",
      ],
      description1: "ASUS",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "82726182",

      name: "ASUS",
      itemImg: [
        "images/6494331_rd.png",
        "images/6494331_sd.jpeg",
        "images/6494331cv1d.jpeg",
        "images/6494331cv3d.jpeg",
        "images/6494331ld.jpeg",
      ],
      description1: "ASUS",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8172811",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6494580_sd.webp",
        "images/6494580cv11d.jpeg",
        "images/6494331cv1d.jpeg",
        "images/6494331cv3d.jpeg",
        "images/6494331ld.jpeg",
      ],
      description1: "ASUS Zebook - Silver",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "777272",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6535501_sd.png",
        "images/6535501_rd.jpeg",
        "images/6535501ld.jpeg",
        "images/6535501cv1d.jpeg",
        "images/6535501cv3d.jpeg",
      ],
      description1: "ASUS Zebook - Silver",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "881737",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6494642_sd.png",
        "images/6494642_rd.jpeg",
        "images/6494642ld.jpeg",
        "images/6494642cv1d.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1727377",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6486485_sd.webp",
        "images/6486485ld.jpeg",
        "images/6486485cv1d.jpeg",
        "images/6486485cv3d.jpeg",
        "images/6486485cv4d.jpeg",
        "images/66486485cv7d.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "447627",

      name: "ASUS Zenbook",
      itemImg: ["images/6494637_sd.png"],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "881837",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6494637_rd.webp",
        "images/6494637ld.jpeg",
        "images/6494637cv1d.jpeg",
        "images/6513491_sd.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1183813",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6513491cv14d.webp",
        "images/6513491cv16d.jpeg",
        "images/6494637cv1d.jpeg",
        "images/6513491_sd.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8818371",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6513491cv14d.webp",
        "images/6513491cv16d.jpeg",
        "images/6494637cv1d.jpeg",
        "images/6494580_sd.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4718372",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6508083_sd.webp",
        "images/6508083_rd.jpeg",
        "images/6508083cv1d.jpeg",
        "images/6508083cv3d.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1988818",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6508083cv4d.webp",
        "images/6508083cv7d.jpeg",
        "images/6508083cv3d.jpeg",
        "images/6508083cv1d.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8176274",

      name: "ASUS Zenbook",
      itemImg: [
        "images/6494331_sd.png",
        "images/6494331_rd.jpeg",
        "images/6494331ld.jpeg",
        "images/6494331cv1d.jpeg",
        "images/6494331cv3d.jpeg",
      ],
      description1: "ASUS Zenbook - Black",
      description2: "",
      newItemPrice: "1500",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 16,
      rom: 1000,
      screen: 16,
      brand: "ASUS",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "516241",

      name: "HP Mini Pavilon",
      itemImg: [
        "images/6515546_sd.png",
        "images/6515546_rd.jpeg",
        "images/6515546ld.jpeg",
        "images/6515546cv1d.jpeg",
      ],
      description1: "HP Pavilon Mini",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "HP",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "7665172",

      name: "HP Pavilon",
      itemImg: [
        "images/6515546cv7d.webp",
        "images/6502179_sd.jpeg",
        "images/6502179_rd.jpeg",
        "images/6502179ld.jpeg",
        "images/6502179cv1d.jpeg",
      ],
      description1: "HP Pavilon ",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "HP",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1762728",

      name: "Omen",
      itemImg: [
        "images/6503849_sd.png",
        "images/6503849_rd.jpeg",
        "images/6503849ld.jpeg",
        "images/6503849cv1d.jpeg",
        "images/6503849cv4d.jpeg",
      ],
      description1: "Omen",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "Omen",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4762911",

      name: "Omen",
      itemImg: [
        "images/6503845_rd.png",
        "images/6503845ld.jpeg",
        "images/6503845cv1d.jpeg",
      ],
      description1: "Omen",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "Omen",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "848828",
      name: "Omen",
      itemImg: [
        "images/6503845_rd.png",
        "images/6503845ld.jpeg",
        "images/6503845cv1d.jpeg",
      ],
      description1: "Omen",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "Omen",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "484828",
      name: "HP Elite Pro Z20",
      itemImg: [
        "images/6502185_sd.png",
        "images/6502185_rd.jpeg",
        "images/6502185cv1d.jpeg",
      ],
      description1: "HP Elite Pro Z20",
      description2: "",
      newItemPrice: "980",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 13,
      brand: "HP",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1989383",
      name: "HP Elite Pro Z20",
      itemImg: [
        "images/6499753_sd.webp",
        "images/6499753_rd.jpeg",
        "images/6499753ld.jpeg",
        "images/6499753cv1d.jpeg",
        "images/6499753cv3d.jpeg",
      ],
      description1: "HP Elite Pro Z20",
      description2: "",
      newItemPrice: "980",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 13,
      brand: "HP",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "919183",
      name: "Microsoft",
      itemImg: [
        "images/6505202cv14d.png",
        "images/6505202cv11d.jpeg",
        "images/6505202_sd.jpeg",
        "images/6505202cv12d.jpeg",
        "images/6505202cv15d.jpeg",
      ],
      description1: "Microsoft",
      description2: "",
      newItemPrice: "980",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 4,
      rom: 256,
      screen: 13,
      brand: "Microsoft",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9183891",
      name: "Omen",
      itemImg: [
        "images/6503845_rd.png",
        "images/6503845ld.jpeg",
        "images/6503845cv1d.jpeg",
      ],
      description1: "Omen",
      description2: "",
      newItemPrice: "1000",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 512,
      screen: 16,
      brand: "Omen",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "949918",
      name: "ASUS Zenbook",
      itemImg: [
        "images/6498803ld.png",
        "images/6498803cv1d.jpeg",
        "images/6498803cv4d.jpeg",
        "images/6498803cv7d.jpeg",
        "images/6498803_rd.jpeg",
      ],
      description1: "ASUS Zenbook",
      description2: "",
      newItemPrice: "1300",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 1000,
      screen: 16,
      brand: "asus",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9484819",
      name: "HP Elite",
      itemImg: [
        "images/6517655_sd.png",
        "images/6517655cv11d.jpeg",
        "images/6517655cv12d.jpeg",
      ],
      description1: "HP Elite",
      description2: "",
      newItemPrice: "1300",
      oldItemPrice: "$544",
      itemTotal: "630",
      ram: 8,
      rom: 1000,
      screen: 16,
      brand: "HP",
      category: "Computers",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },
  ],


  
  laptop: {},
};

const ComputerReducer = (state = initState, action) => {
  switch (action.type) {
    case "PRODUCT":
      return {
        ...state,
        laptop: state.laptops.find(
          (laptop) => laptop.id === parseInt(action.id)
        ),
      };
    default:
      return state;
  }
};
export default ComputerReducer;