const initState = {
  games: [
    {
      id: "7298",

      name: "Xbox",
      itemImg: [
        "images/pngfind.com-xbox-controller-png-9253.webp",
        "images/51vRipjKjML._SL1200_.jpg",
        "images/61-uVCKZhtL._SL1200_.jpg",
      ],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "89924",

      name: "Xbox",
      itemImg: [
        "images/51hV2qz3WuL._AC_SL1080_.webp",
        "images/51GONCGpiWL._AC_SL1200_.jpg",
        "images/51MeEV7Bu6L._AC_SL1200_.jpg",
        "images/41lfqMsh3+S._AC_SL1200_.jpg",
      ],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "428742",

      name: "Xbox",
      itemImg: ["images/pngfind.com-xbox-360-console-png-4295427.webp"],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "740297",

      name: "Xbox",
      itemImg: ["images/pngfind.com-xbox-live-png-4855673.webp"],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "572942",

      name: "Xbox",
      itemImg: [
        "images/pngfind.com-xbox-controller-png-9253.webp",
        "images/51e2Q-TWUEL._SL1200_.jpg",
        "images/51J7qkVOezL._SL1000_.jpg",
        "images/61jkjQejpyL._SL1000_.jpg",
      ],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "84272",

      name: "Xbox",
      itemImg: ["images/61RA2sUPu+L._SL1000_.webp"],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1914",

      name: "Xbox 3",
      itemImg: [
        "images/61BEpu+HTAL._SL1500_.webp",
        "images/612YEtRWckL._SL1500_.jpg",
        "images/51eOztNdCkL._SL1500_.jpg",
      ],
      description1: "PS 5",
      description2: "",
      newItemPrice: "630",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1077",

      name: "PS 2",
      itemImg: [
        "images/61pETE6v4vL._SL1500_.webp",
        "images/51EhttI30bL._SL1200_.jpg",
      ],
      description1: "PS 2",
      description2: "",
      newItemPrice: "400",
      oldItemPrice: "$544",
      itemTotal: "400",
      brand: "ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1890",

      name: "PS 4",
      itemImg: [
        "images/pngfind.com-ps4-png-520012.webp",
        "images/71-WrFQo1FL._SL1500_.jpg",
        "images/71XrnwP7yjL._SL1500_.jpg",
        "images/ipad2.webp",
        "images/ipad2.webp",
      ],
      description1: "PS 4",
      description2: "",
      newItemPrice: "540",
      oldItemPrice: "$544",
      itemTotal: "540",
      brand: "Ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1131",

      name: "PS 2",
      itemImg: [
        "images/81bHi3vo88L._SL1500_.webp",
        "images/81HMFRvlxiL._SL1500_.jpg",
      ],
      description1: "PS 2",
      description2: "",
      newItemPrice: "620",
      oldItemPrice: "$544",
      itemTotal: "620",
      brand: "Ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1001",

      name: "PS 5",
      itemImg: [
        "images/51C0Nbg5QNL._SL1500_.webp",
        "images/61U86M+XTlL._SL1500_.jpg",
        "images/61kg+jnrz0L._SL1500_.jpg",
        "images/61T9Sylvn6L._SL1500_.jpg",
        "images/51fySIAYsCL._SL1450_.jpg",
      ],
      description1: "PS 5",
      description2: "",
      newItemPrice: "600",
      oldItemPrice: "$544",
      itemTotal: "600",
      brand: "Ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8210",

      name: "PS 5",
      itemImg: [
        "images/61WnudgMYwL._AC_SL1500_.webp",
        "images/61BQMgRgqfL._AC_SL1500_.jpg",
        "images/61muxUUn0NL._AC_SL1500_.jpg",
      ],
      description1: "PS 5",
      description2: "",
      newItemPrice: "330",
      oldItemPrice: "$544",
      itemTotal: "330",
      brand: "Ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8320",

      name: "PS 4",
      itemImg: [
        "images/pngfind.com-ps4-cover-png-4164715.webp",
        "images/41A5YRynOAL._SL1000_.jpg",
        "images/51tbWVPtckL._AC_SL1500_.jpg",
      ],
      description1: "PS 4",
      description2: "",
      newItemPrice: "850",
      oldItemPrice: "$544",
      itemTotal: "850",
      brand: "Ps",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9293",

      name: "PS 4",
      itemImg: [
        "images/pngfind.com-ps4-pro-png-2649225.webp",
        "images/51SmNTnYT2L._SL1500_.webp",
        "images/61dXkVvoq6L._SL1500_.jpg",
        "images/718xi8SwUUL._SL1500_.jpg",
      ],
      description1: "PS 4",
      description2: "",
      newItemPrice: "900",
      oldItemPrice: "$544",
      itemTotal: "900",
      brand: "PS",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "88204",

      name: "Xbox",
      itemImg: [
        "images/717JafCjCAL._SL1500_.webp",
        "images/712VxqaHDvL._SL1500_.jpg",
        "images/8192qTuzoEL._SL1500_.jpg",
      ],
      description1: "XBOX",
      description2: "",
      newItemPrice: "1200",
      oldItemPrice: "$544",
      itemTotal: "1000",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9282",

      name: "Xbox",
      itemImg: [
        "images/61gjug2NzvL._SL1500_.webp",
        "images/616-K1n0NeL._SL1500_.jpg",
        "images/61H-v5npLZL._SL1500_.jpg",
      ],
      description1: "Lorem ipsum dolor sit amet",
      description2: "",
      newItemPrice: "1112",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "Xbox",
      category: "Gaming",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },
  ],

  game: {},
};

const GameReducer = (state = initState, action) => {
  switch (action.type) {
    case "GAME":
      return {
        ...state,
        game: state.games.find((game) => game.id === parseInt(action.id)),
      };
    default:
      return state;
  }
};
export default GameReducer;
