const initState = {
  tvs: [
    {
      id: "494991",

      name: "Hisense",
      itemImg: ["images/try8.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "949910",

      name: "Hisense",
      itemImg: ["images/tyr77.png"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9492891",

      name: "Hisense",
      itemImg: ["images/try6.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "944289",

      name: "Hisense",
      itemImg: ["images/try5.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "492991",

      name: "Hisense",
      itemImg: ["images/try4.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4924294",

      name: "Hisense",
      itemImg: ["images/try3.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4299911",

      name: "Hisense",
      itemImg: ["images/try2.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "849291",

      name: "Hisense",
      itemImg: ["images/pngfind.com-apple-tv-png-6649938.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "484899",

      name: "Hisense",
      itemImg: ["images/pngfind.com-wall-led-tv-png-6207876.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9193933",

      name: "Hisense",
      itemImg: ["images/pngfind.com-tv-top-view-png-3722350.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "825838",

      name: "Hisense",
      itemImg: ["images/pngfind.com-tv-png-6141897.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "881848",

      name: "Hisense",
      itemImg: ["images/pngfind.com-tv-png-1036874.webp"],
      description1: "Hisense TV",
      description2: "",
      newItemPrice: "928",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "hisense",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "482194",

      name: "LG",
      itemImg: ["images/pngfind.com-tv-png-604165.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "489192",

      name: "LG",
      itemImg: ["images/pngfind.com-tv-frame-png-2260206.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "482819",

      name: "LG",
      itemImg: ["images/pngfind.com-television-png-3239976.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4881893",

      name: "LG",
      itemImg: ["images/pngfind.com-smart-tv-png-6086400.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4881893",

      name: "LG",
      itemImg: ["images/pngfind.com-apple-tv-png-6650041.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9429919",

      name: "LG",
      itemImg: ["images/pngfind.com-samsung-tv-png-5392498.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "999",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 32,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4982919",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-tv-png-5392548.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "9199332",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-3123133.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4929101",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-3123130.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "1129291",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-3123104.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "499213",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-2220829.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "199194",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-2220242.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4849193",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-1457864.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "981882",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-1457255.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4929911",

      name: "Samsung",
      itemImg: ["images/pngfind.com-samsung-led-tv-png-1456870.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "49199819",

      name: "Samsung",
      itemImg: ["images/pngfind.com-live-tv-png-5294774.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "8191938",

      name: "Samsung",
      itemImg: ["images/pngfind.com-led-tvs-png-5392992.webp"],
      description1: "Samsung TV",
      description2: "",
      newItemPrice: "1600",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "samsung",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "5819184",

      name: "LG",
      itemImg: ["images/pngfind.com-led-tv-png-lg-5994058.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4829198",

      name: "Toshiba",
      itemImg: ["images/pngfind.com-led-tv-images-png-2500423.webp"],
      description1: "Toshiba TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "toshiba",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "199883",

      name: "Toshiba",
      itemImg: ["images/pngfind.com-led-tv-images-png-2500416.webp"],
      description1: "Toshiba TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "toshiba",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "482919",

      name: "Toshiba",
      itemImg: ["images/pngfind.com-hd-tv-png-6136704.webp"],
      description1: "Toshiba TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "toshiba",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "489199842",

      name: "LG",
      itemImg: ["images/pngfind.com-flat-screen-tv-png-3193976.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },

    {
      id: "4892919",

      name: "LG",
      itemImg: ["images/pngfind.com-flat-screen-tv-on-3513033.webp"],
      description1: "LG TV",
      description2: "",
      newItemPrice: "300",
      oldItemPrice: "$544",
      itemTotal: "630",
      brand: "lg",
      size: 43,
      category: "TV",
      color: "🇺🇦",
      OS: "🫶🏼",
      CPU: "🁼",
      smop: "😘",
      ct: "🌕",
      aom: "🌑",
    },
  ],

  tv: {},
};

const TvReducer = (state = initState, action) => {
  switch (action.type) {
    case "TV":
      return {
        ...state,
        tv: state.tvs.find((tv) => tv.id === parseInt(action.id)),
      };
    default:
      return state;
  }
};
export default TvReducer;
